class427s/class427s/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import static
from django.contrib import admin

from class427s import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r's/', include('stu.urls', namespace='s')),
    url(r'u/', include('uauth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class427s/stu/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from stu import views
from rest_framework.routers import SimpleRouter

router = SimpleRouter()
router.register(r'student', views.StudentEdit)

urlpatterns = [
    url(r'^index/', login_required(views.index)),
    url(r'stu_page', login_required(views.stu_page)),
    url(r'get/', views.get),
    url(r'^add_stu/', login_required(views.add_stu), name='add'),
    url(r'add_stu_info/(?P<stu_id>\d+)/', login_required(views.add_stu_info), name='addinfo')
]


urlpatterns += router.urls

class427s/uauth/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from uauth import views


urlpatterns = [
    url(r'^regist/', views.regiter),
    url(r'^login/$', views.my_login),
    url(r'^logout/', views.logout),
    url(r'^dj_login/', views.djlogin),
    url(r'^dj_regist', views.djregist),
    url(r'^dj_logout', views.djlogout)
]

class427s/stu/models.py
from django.db import models

# Create your models here.


class Student(models.Model):

    s_name = models.CharField(max_length=10)
    s_tel = models.CharField(max_length=11)

    class Meta:
        db_table = 'day51_stu'


class StudentInfo(models.Model):

    i_addr = models.CharField(max_length=20)
    i_image = models.ImageField(upload_to='upload', null=True)
    s = models.OneToOneField(Student)

    class Meta:
        db_table = 'day51_stu_info'


class Visit(models.Model):
    v_url = models.CharField(max_length=30)
    v_times = models.IntegerField()

    class Meta:
        db_table = 'visit'

class427s/uauth/models.py
from django.db import models

# Create your models here.


class Users(models.Model):

    u_name = models.CharField(max_length=10)
    u_password = models.CharField(max_length=100)
    u_ticket = models.CharField(max_length=30, null=True)

    class Meta:
        db_table = 'day51_users'

class427s/stu/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from stu.serializers import StudentSerializer

from stu.models import Student, StudentInfo

import logging

from rest_framework import mixins, viewsets

logger = logging.getLogger('stu')


def index(request):

    if request.method == 'GET':
        # 获取所有学生信息，先确认有没有cookie
        # ticket = request.COOKIES.get('ticket')
        # if not ticket:
        #     return HttpResponseRedirect('/u/login')
        # # 判断当前浏览的网页是否有相关的Cookie
        # if Users.objects.filter(u_ticket=ticket).exists():
        stuinfos = StudentInfo.objects.all()
        logger.info('获取学生信息成功')
        return render(request, 'index.html', {'stuinfos': stuinfos})
        # else:
        #     return HttpResponseRedirect('/u/login')


def stu_page(request):

    if request.method == 'GET':
        page_id = request.GET.get('page_id', 1)
        stuinfos = StudentInfo.objects.all()
        paginator = Paginator(stuinfos, 5)
        page = paginator.page(int(page_id))
        return render(request, 'index.html', {'stuinfos': page})


def add_stu(request):

    if request.method == 'GET':
        return  render(request, 'add_stu.html')

    if request.method == 'POST':
        # 跳转到添加学生详情页面
        name = request.POST.get('name')
        tel = request.POST.get('tel')

        stu = Student.objects.create(
            s_name=name,
            s_tel=tel
        )
        return HttpResponseRedirect(
            reverse('s:addinfo', kwargs={'stu_id': stu.id})
        )


def add_stu_info(request, stu_id):

    if request.method == 'GET':

        return render(request, 'add_stu_info.html', {'stu_id': stu_id})

    if request.method == 'POST':
        stu_id = request.POST.get('stu_id')
        addr = request.POST.get('addr')
        # 添加头像图片
        img = request.FILES.get('img')
        StudentInfo.objects.create(
            i_addr=addr,
            s_id=stu_id,
            i_image=img
        )
        return HttpResponseRedirect('/s/index/')


def get(request):

    if request.method == 'GET':

        return render(request, 'get.html')


class StudentEdit(mixins.ListModelMixin,  # 获取所有的资源
                  # 获取具体的某个资源
                  mixins.RetrieveModelMixin,
                  mixins.UpdateModelMixin,
                  mixins.CreateModelMixin,
                  mixins.DestroyModelMixin,
                  viewsets.GenericViewSet):

    # 查询所有信息
    queryset = Student.objects.all()
    # 序列化
    serializer_class = StudentSerializer

class427s/uauth/views.py
import random, time

from django.contrib import auth
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import auth
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

# Create your views here.
# 导入自己写的users模块
from uauth.models import Users
# 导入系统自带的users
from django.contrib.auth.models import User


def regiter(request):

    if request.method == 'GET':
        return render(request, 'day6_regist.html')

    if request.method == 'POST':
        # 注册
        name = request.POST.get('name')
        password = request.POST.get('password')

        # 对密码进行加密
        password = make_password(password)

        Users.objects.create(u_name=name, u_password=password)

        return HttpResponseRedirect('/u/login/')


def my_login(request):
    if request.method == 'GET':
        return render(request, 'day6_login.html')

    if request.method == 'POST':
        # 如果登录成功，绑定参数到Cookie， set_cookie
        name = request.POST.get('name')
        password = request.POST.get('password')

        if Users.objects.filter(u_name=name).exists():
            user = Users.objects.get(u_name=name)
            if check_password(password, user.u_password):
                ticket = ''
                for i in range(15):
                    ticket += random.choice('abcdefghijklmnopqrstuvwxyz0123456789')
                now_time = int(time.time())
                ticket = 'TK_' + ticket + str(now_time)
                # 绑定令牌到本地浏览器Cookie里面
                response = HttpResponseRedirect('/s/index/')
                # max_age表示这个Cookie的存在时间为50s，超过时间则需要重新登录
                response.set_cookie('ticket', ticket, max_age=5000)
                # 存令牌到服务端
                user.u_ticket = ticket
                user.save()
                return response
            else:
                return HttpResponse('用户密码错误')
        else:
            return HttpResponse('用户不存在')


# 使用django自带的
def login(request):

    if request.method == 'GET':
        return render(request, 'login.html')
    if request.method == 'POST':
        r = request.POST
        name = r['name']
        password = r['password']

        user = auth.authenticate(username=name, password=password)

        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/s/index/')
        else:
            return HttpResponse('用户名或密码错误。')


def logout(request):

    if request.method == 'GET':
        response = HttpResponseRedirect('/u/login/')
        response.delete_cookie('ticket')
        return response


def djlogin(request):
    if request.method == 'GET':
        return render(request, "login.html")
    if request.method == 'POST':
        name = request.POST.get('name')
        password = request.POST.get('password')

        # 验证用户名和密码，验证通过返回user对象
        user = auth.authenticate(username=name, password=password)
        if user:
            # 验证成功
            auth.login(request, user)
            return HttpResponseRedirect('/s/index/')
        else:
            return HttpResponse('用户名或者密码错误')


def djregist(request):
    if request.method == 'GET':
        return render(request, 'register.html')

    if request.method == 'POST':

        name = request.POST.get('name')
        password = request.POST.get('password')

        User.objects.create_user(username=name, password=password)
        return HttpResponseRedirect('/u/dj_login/')


def djlogout(request):

    if request.method == 'GET':
        auth.logout(request)

        return HttpResponseRedirect('/u/dj_login/')

class427s/templates/add_stu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加学生</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <th>姓名</th>
            <th>电话</th>
        </tr>
        <tr>
            <td><input type="text" name="name"></td>
            <td><input type="text" name="tel"></td>
        </tr>
        <tr>
            <td><input type="submit" value="提交"></td>
        </tr>
    </table>
</form>
</body>
</html>

class427s/templates/add_stu_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加学生详情</title>
</head>
<body>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
{#    这里悄悄的传入了学生的id但是将其隐藏起来不显示#}
    <input type="hidden" value="{{ stu_id }}" name="stu_id">
    地址：<input type="text" name="addr">
    头像：<input type="file" name="img">
    <input type="submit" value="提交">
</form>
</body>
</html>

class427s/templates/day6_login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0"> 
	<title>登录界面</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css" />
	<!--必要样式-->
    <link href="/static/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/demo.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/loaders.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

	<script type="text/javascript">
		function login(){
			err_name = $('#err_name').val()
			err_password = $('#err_password').val()
			if(err_name){
				alert(err_name)
			}else if(err_password){
				alert(err_password)
			}
		}
	</script>

</head>
<body onload="login()">
	<div class='login'>
	  <div class='login_title'>
	    <span>管理员登录</span>
	  </div>
		<input type="hidden" id="err_name" value="{{name}}"/>
		<input type="hidden" id="err_password" value="{{password}}"/>
		<form action="" method="post">

            {% csrf_token %}
	  <div class='login_fields'>
	    <div class='login_fields__user'>
	      <div class='icon'>
	        <img alt="" src='/static/img/user_icon_copy.png'>
	      </div>
	      <input required name="name" placeholder='用户名' maxlength="16" type='text' autocomplete="off" value=""/>
	        <div class='validation'>
	          <img alt="" src='/static/img/tick.png'>
	        </div>
	    </div>
	    <div class='login_fields__password'>
	      <div class='icon'>
	        <img alt="" src='/static/img/lock_icon_copy.png'>
	      </div>
	      <input required name="password" placeholder='密码' maxlength="16" type='text' autocomplete="off">
	      <div class='validation'>
	        <img alt="" src='/static/img/tick.png'>
	      </div>
	    </div>
	    <div class='login_fields__submit'>
	      	<input type='submit' value='登录'>
			<input id="regist" type='button' value='注册'>
	    </div>
	  </div>
		</form>
	  <div class='success'>
	  </div>
	  <div class='disclaimer'>
	    <p>欢迎登录后台管理系统</p>
	  </div>
	</div>
	<div class='authent'>
	  <div class="loader" style="height: 44px;width: 44px;margin-left: 28px;">
        <div class="loader-inner ball-clip-rotate-multiple">
            <div></div>
            <div></div>
            <div></div>
        </div>
        </div>
	  <p>认证中...</p>
	</div>
	<div class="OverWindows"></div>
	
    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css" />
	
	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src='/static/js/stopExecutionOnTimeout.js?t=1'></script>
    <script type="text/javascript" src="/static/layui/layui.js"></script>
    <script type="text/javascript" src="/static/js/Particleground.js"></script>
    <script type="text/javascript" src="/static/js/Treatment.js"></script>
    <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>
    <script>
        (function () {
            btn = document.getElementById('regist');
            btn.addEventListener('click',function (ev) {
              window.location = '/u/regist/'
            });
        }())
    </script>

</body>
</html>

class427s/templates/day6_regist.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">
	<title>注册界面</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css" />
	<!--必要样式-->
    <link href="/static/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/demo.css" rel="stylesheet" type="text/css" />
    <link href="/static/css/loaders.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>


</head>
<body onload="login()">
	<div class='login'>
	  <div class='login_title'>
	    <span>注册新账号</span>
	  </div>
    <form action="" method="post">
        {% csrf_token %}

	  <div class='login_fields'>
	    <div class='login_fields__user'>
	      <div class='icon'>
	        <img alt="" src='/static/img/user_icon_copy.png'>
	      </div>
	      <input required name="name" placeholder='用户名' maxlength="16" type='text' autocomplete="off" value=""/>
	        <div class='validation'>
	          <img alt="" src='/static/img/tick.png'>
	        </div>
	    </div>
	    <div class='login_fields__password'>
	      <div class='icon'>
	        <img alt="" src='/static/img/lock_icon_copy.png'>
	      </div>
	      <input required name="password" placeholder='密码' maxlength="16" type='text' autocomplete="off">
	      <div class='validation'>
	        <img alt="" src='/static/img/tick.png'>
	      </div>
	    </div>
	    <div class='login_fields__submit'>
			<input type='submit' value='注册'>
	    </div>
	  </div>
    </form>

	  <div class='success'>
	  </div>
	  <div class='disclaimer'>
	    <p>欢迎注册后台管理系统账号</p>
	  </div>
	</div>
	<div class='authent'>
	  <div class="loader" style="height: 44px;width: 44px;margin-left: 28px;">
        <div class="loader-inner ball-clip-rotate-multiple">
            <div></div>
            <div></div>
            <div></div>
        </div>
        </div>
	  <p>注册中...</p>
	</div>
	<div class="OverWindows"></div>

    <link href="/static/layui/css/layui.css" rel="stylesheet" type="text/css" />

	<script type="text/javascript" src="/static/js/jquery.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src='/static/js/stopExecutionOnTimeout.js?t=1'></script>
    <script type="text/javascript" src="/static/layui/layui.js"></script>
    <script type="text/javascript" src="/static/js/Particleground.js"></script>
    <script type="text/javascript" src="/static/js/Treatment.js"></script>
    <script type="text/javascript" src="/static/js/jquery.mockjax.js"></script>

</body>
</html>

class427s/templates/get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>展示所有学生信息</title>
    <style>
        table{
            border: 1px solid blue;
        }
        th, td{
            border: 1px solid blue;
        }
    </style>
</head>
<body>
    {% csrf_token %}
    <input id='btn' type="button" name="btn" value="获取学生信息">

    <div id="data"></div>
    <div id="div_update_stus"></div>
    <div id="div_add_stus"></div>

{#    <script>#}
        {#原生js写法异步获取数据#}
{#        function getdata(){#}
{#            var btn = document.getElementById('btn');#}
{#            btn.addEventListener('click', function () {#}
{#                var xhr = new XMLHttpRequest();#}
{#                xhr.open('get', 'http://127.0.0.1:8888/s/student/', true);#}
{#                xhr.onreadystatechange = function(){#}
{#                    if(xhr.readyState == 4 && xhr.status == 200){#}
{#                        var obj = JSON.parse(xhr.responseText);#}
{#                        var div = document.getElementById('data');#}
{#                        for(var i = 0; i < obj.length; i++){#}
{#                            var h3 = document.createElement('h3');#}
{#                            var name = obj[i]['s_name'];#}
{#                            var tel = obj[i]['s_tel'];#}
{#                            var addr = obj[i]['s_addr'];#}
{#                            var id = obj[i]['s_id'];#}
{#                            h3.innerHTML = id + ' ' + name + '  ' + tel + '  ' + addr;#}
{#                            div.appendChild(h3);#}
{#                        }#}
{#                    }#}
{#                };#}
{#                xhr.send();#}
{#            });#}
{#        }#}
{#        getdata();#}
{#    </script>#}

    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <script>
        {#使用jQuery写法Ajax异步获取数据#}
        $(function () {
            $('#btn').on('click', function () {
                var dataurl = 'http://127.0.0.1:8888/s/student/';
                $.ajax({url: dataurl, type: 'get', success: function (obj) {}});
                $.get('/s/student/', function(aaa) {
                    var s = '<table><tr><th>ID</th> <th>姓名</th> <th>电话</th> <th>地址</th> <th>操作</th></tr>';
                    console.log(aaa.data)
                    aaa = aaa.data
                    for(var i = 0; i < aaa.length; i++){
                        s += '<tr><td>' + aaa[i].id + '</td><td>' + aaa[i].s_name + '</td>' +
                            '<td>' + aaa[i].s_tel + '</td><td>' + aaa[i].s_addr + '</td>' +
                            '<td><a href="javascript:;" onclick="update_stu(' + aaa[i].id + ')">编辑</a>|' +
                            '<a href="javascript:;" onclick="del_stu(' + aaa[i].id + ')">删除</a></td></tr>';

                    }
                    s += '</table><br> <input type="button" id="add" value="添加学生" onclick="add_stu()">';

                    $('#data').html(s)
                },'json');
            });
        });
        function add_stu() {
            var s = '姓名：<input id="new_name" type="text" name="new_name">' +
                '电话：<input id="new_tel" type="text" name="new_tel">' +
                '<input type="button" value="提交" onclick="add()">';

            $('#div_add_stus').html(s);
        }
        function add() {
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            var s_name = $('#new_name').val();
            var s_tel = $('#new_tel').val();
            $.ajax({
                url: '/s/student/',
                type: 'POST',
                data: {'s_name': s_name, 's_tel': s_tel},
                headers: {'X-CSRFToken': csrf},
                success: function (msg) {
                    alert('添加成功')
                    $('#new_name').hide()
                    $('#new_tel').hide()

                },
                error: function (msg) {
                    alert('添加失败')
                },
            })
        }

        function del_stu(i) {
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url: '/s/student/' + i + '/',
                type: 'DELETE',
                dateType: 'json',
                headers: {'X-CSRFToken': csrf},
                success: function (msg) {
                    alert('删除成功');
                },
                error: function (msg) {
                    alert('删除失败');
                },
            });
        };
        function update_stu(i) {
            var s = '姓名：<input id="s_name" type="text" name="name">' +
                '电话：<input id="s_tel" type="text" name="tel">' +
                '<input type="button" value="提交" onclick="update(' + i + ')">';

            $('#div_update_stus').html(s);
        };
        function update(i) {
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            var s_name = $('#s_name').val();
            var s_tel = $('#s_tel').val();
            $.ajax({
                url: '/s/student/' + i + '/',
                type: 'PATCH',
                data: {'s_name': s_name, 's_tel': s_tel},
                dataType: 'json',
                headers: {'X-CSRFToken': csrf},
                success: function (msg) {
                    alert('修改成功')
                },
                error: function (msg) {
                    alert('修改失败')
                },

            })
        }


    </script>
</body>
</html>

class427s/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>所有学生信息</title>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        table{
            border: 1px solid blue;
            border-bottom: none;
        }
        #stu_info td{
            border-bottom: 1px solid blue;
            border-right: 1px solid blue;
        }
        .r{
            border-right: none !important;
        }
    </style>
</head>
<body>

    <table id="stu_info">
        <tr>
            <td>头像</td>
            <td>ID</td>
            <td>姓名</td>
            <td>电话</td>
            <td class="r">地址</td>
        </tr>

        {% for stuinfo in stuinfos %}
            <tr>
            <td>
                {% if stuinfo.i_image %}
                    <img src="/media/{{ stuinfo.i_image }}" width="24" height="24" alt="头像">
                {% endif %}
            </td>
            <td>{{ stuinfo.id }}</td>
            <td>{{ stuinfo.s.s_name }}</td>
            <td>{{ stuinfo.s.s_tel }}</td>
            <td class="r">{{ stuinfo.i_addr }}</td>
            </tr>
        {% endfor %}

    </table>
        <h4>{% if not stuinfos.paginator.num_pages %}

            {% else %}
            一共{{ stuinfos.paginator.num_pages }}页
            /共{{ stuinfos.paginator.count }}条数据  当前第 {{ stuinfos.number }} 页
            
            {% endif %}
        </h4>

        {% if stuinfos.has_previous %}
            <a href="/s/stu_page/?page_id={{ stuinfos.previous_page_number }}">上一页</a>
        {% endif %}


        {% if stuinfos.has_next %}
            <a href="/s/stu_page/?page_id={{ stuinfos.next_page_number }}">下一页</a>
        {% endif %}

        {% for i in stuinfos.paginator.page_range %}
            <a href="/s/stu_page/?page_id={{ i }}">{{ i }}</a>
        {% endfor %}

        {% if stuinfos.paginator.num_pages %}

            <input id="btn" type="button" value="跳转">
            第 <input id="jump_input" type="text" name="jump_page" size="1" > 页

            <script>
                (function (){
                    var btn = document.getElementById('btn');
                    btn.addEventListener('click', function () {
                        var page = document.getElementById('jump_input').value;
                        if(page>=1 && page<=5){
                            console.log(page);
                            window.location = '/s/stu_page/?page_id=' + page ;
                        }
                        else {
                            alert('请输入正确的页码')
                        }
                    });
                }());
            </script>
        {% endif %}


        <h4>-----------我是分割线---------------</h4>
        {#方法一#}
        <a href="{% url 's:add' %}">添加学生</a>
        {#方法二#}
        {#<a href="/s/add_stu/">添加学生</a>#}
        <a href="/u/logout/">退出登录</a>

        {% if not stuinfos.paginator.num_pages %}
        <a href="/s/stu_page/">分页显示</a>
        {% else %}
        <a href="/s/index/">整体显示</a>
        {% endif %}


</body>
</html>

class427s/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        登录姓名： <input type="text" name="name">
        登录密码： <input type="password" name="password">
        <input type="submit" value="提交">
    </form>

</body>
</html>

class427s/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        注册姓名： <input type="text" name="name">
        注册密码： <input type="password" name="password">
        <input type="submit" value="提交">
    </form>
</body>
</html>